### ISSUE TITLE
Curiosidade sobre a lógica do código

### ISSUE THREAD

**Issue by VictorManoel** [LuizPedroSM/DIO-Node-Desafios#1]
Como você chegou no cálculo para encontrar a posição do index? Principalmente do sentido contrário, se baseou em aritmética modular? Seu código ficou muito bom!!!

**Comment by LuizPedroSM** [comment]
Gincana no Acampamento
Informações importantes do desafio:
... agrupar os alunos em um círculo (organizado no sentido anti-horário)....
... quando o valor que consta na ficha é par, a contagem é feita no sentido horário e quando o valor que consta na ficha é ímpar, a contagem é feita no sentido anti-horário.

O algoritmo:
Cria a lista no sentido anti-horário do círculo de alunos.
Ou seja quando percorro a lista de forma normal eu giro no sentido anti-horário que é quando o valor da ficha é ímpar
Dessa forma para achar a posição da próxima criança :
basta pegar o remainder(resto) de ( index(a posição da criança atual) + o valor da ficha) com o tamanho da roda.
Assim acha a criança que perdeu. E pega o valor da ficha.

Se o valor da ficha for ímpar tem que voltar o index uma posição. Já que começa da criança ao lado do sentido anti-horário e no par não precisa fazer nada já que o index vai está na posição certa que é a criança do sentido horário

Vale lembra que o % é remainder. Existe diferença entre remainder vs modulo.
Eles funcionam de forma igual somente se o numero for positivo. O que nem sempre acontece nesse desafio.

No caso de ser par. Para 'percorrer' a lista ao contrario.
Primeiro se pega o resto da divisão da ficha com a roda. Para saber quantas 'casas' devem andar.
depois diminui com a posição atual já que está voltando. (se o resultado for negativo o remainder vai ser 0 ou negativo, o que não acontece no mod).
e pega remainder(resto) com o tamanho da roda.
Se o index for negativo basta pegar a roda e somar com o index.

**Comment by VictorManoel** [comment]
Muito Bom!!!
